# Generated by Django 6.0.5 on 2026-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_high_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Draft', max_length=10)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
            options={
                'verbose_name': 'auction',
                'db_table': 'auction',
            },
        ),
    ]
